version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_SERVICE=app
    depends_on:
      - mysql
      - mailhog
    ports:
      - "5173:5173"   # Vite
      - "8000:8000"   # Artisan serve
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance
      MYSQL_USER: finance
      MYSQL_PASSWORD: finance
    ports: ["3306:3306"]
    volumes:
      - dbdata:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
volumes:
  dbdata:
